version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 83:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./php:/var/www/html

  php:
    image: php:7.4-fpm
    volumes:
      - ./php:/var/www/html
